# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dl-lecture-notes',
                'doc_host': 'https://sayan.github.io',
                'git_url': 'https://github.com/sayan/dl-lecture-notes',
                'lib_path': 'dl_lecture_notes'},
  'syms': {'dl_lecture_notes.core': {'dl_lecture_notes.core.foo': ('core.html#foo', 'dl_lecture_notes/core.py')}}}
